version: "2"
run:
  concurrency: 4
  build-tags:
    - containers_image_openpgp
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - unconvert
  settings:
    errcheck:
      check-blank: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
