name: Release Create

on:
  push:
    tags:
      - 'v*'
      - '!*cloud'

jobs:
  release-create:
    if: ${{ ! contains(github.ref_name, 'v0.5.') && ! contains(github.ref_name, 'v0.6.') && ! contains(github.ref_name, 'v0.7.') }}
    uses: apecloud/apecloud-cd/.github/workflows/release-create.yml@v0.1.42
    with:
      APECD_REF: "v0.1.42"
    secrets: inherit
